const ADD_TITLE = 'ADD_TITLE';
const REMOVE_TITLE = 'REMOVE_TITLE';
const REMOVE_TITLE_CONFIRM = 'REMOVE_TITLE_CONFIRM';
const REMOVE_TITLE_CANCEL = 'REMOVE_TITLE_CANCEL';
const CHANGE_FILTER = 'CHANGE_FILTER';
const SWITCH_VIEW = 'SWITCH_VIEW';
const SWITCH_SORTING = 'SWITCH_SORTING';
const INCREASE_SCORE = 'INCREASE_SCORE';
const DECREASE_SCORE = 'DECREASE_SCORE';

export {
  ADD_TITLE,
  REMOVE_TITLE,
  REMOVE_TITLE_CONFIRM,
  REMOVE_TITLE_CANCEL,
  SWITCH_VIEW,
  SWITCH_SORTING,
  CHANGE_FILTER,
  DECREASE_SCORE,
  INCREASE_SCORE,
};
